
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs
  name: nodejs
spec:
  ports:
  - port: 3200
    protocol: TCP
    targetPort: 3200
    nodePort: 32001
  selector:
    app: nodejs
  type: NodePort
status:
  loadBalancer: {}